export const exams = [
  { id:"jee-main", name:"JEE Main", full:"Joint Entrance Examination Main", category:"Engineering", color:"#f97316", icon:"⚙️", difficulty:"High", diffScore:3, frequency:"Twice a year", seats:"~11 lakh", salary:"₹8-25 LPA", duration:"4 years", syllabus:["Physics: Mechanics, Thermodynamics, Electrostatics, Optics, Modern Physics","Chemistry: Physical, Organic & Inorganic Chemistry","Mathematics: Algebra, Calculus, Coordinate Geometry, Trigonometry"], topics:{"Physics":["Mechanics","Thermodynamics","Electrostatics","Optics","Modern Physics","Waves","Current Electricity"],"Chemistry":["Physical Chemistry","Organic Chemistry","Inorganic Chemistry","Chemical Bonding","Equilibrium"],"Mathematics":["Algebra","Calculus","Coordinate Geometry","Trigonometry","Statistics","Vectors"]}, pattern:{duration:"3 hours",questions:"90 MCQs",total:"300 marks",negative:"Yes (-1)"}, cutoff:[{year:2024,general:90.7,obc:75.3,sc:54.0,st:44.1},{year:2023,general:88.4,obc:72.1,sc:51.9,st:42.0}], books:["HC Verma – Concepts of Physics","NCERT Chemistry XI & XII","RD Sharma / Arihant Maths","DC Pandey – Electricity & Magnetism"], eligibility:"Class 12 with PCM. Min 75% marks.", tips:["Master NCERT before advanced books","Solve 10+ years previous papers","Focus on weak chapters","Attempt mocks under exam conditions"] },
  { id:"jee-adv", name:"JEE Advanced", full:"Joint Entrance Examination Advanced", category:"Engineering", color:"#ea580c", icon:"🏆", difficulty:"Extremely High", diffScore:5, frequency:"Once a year", seats:"~17,000", salary:"₹15-50 LPA", duration:"4 years", syllabus:["Physics: Full JEE syllabus at deeper level","Chemistry: Full JEE syllabus at deeper level","Mathematics: Full JEE syllabus at deeper level"], topics:{"Physics":["Mechanics (Advanced)","Thermodynamics (Advanced)","Electrostatics (Advanced)","Optics (Advanced)","Modern Physics"],"Chemistry":["Physical Chemistry (Advanced)","Organic Chemistry (Advanced)","Inorganic Chemistry (Advanced)"],"Mathematics":["Algebra (Advanced)","Calculus (Advanced)","Coordinate Geometry (Advanced)","Complex Numbers"]}, pattern:{duration:"6 hours (2 papers)",questions:"54 per paper",total:"360 marks",negative:"Yes (varies)"}, cutoff:[{year:2024,general:109,obc:98,sc:54,st:54},{year:2023,general:91,obc:82,sc:45,st:45}], books:["IIT JEE previous year papers","Irodov – Problems in Physics","Morrison Boyd – Organic Chemistry","Hall & Knight – Higher Algebra"], eligibility:"Top 2.5 lakh JEE Main qualifiers. Max 2 attempts.", tips:["Concept clarity over quantity","Practice IIT previous papers extensively","Time management is critical","Don't ignore any topic"] },
  { id:"neet-ug", name:"NEET UG", full:"National Eligibility cum Entrance Test UG", category:"Medical", color:"#10b981", icon:"🩺", difficulty:"Very High", diffScore:4, frequency:"Once a year", seats:"~1.08 lakh", salary:"₹6-20 LPA", duration:"5.5 years", syllabus:["Physics: Class 11 & 12 NCERT","Chemistry: Physical, Organic, Inorganic (NCERT)","Biology: Botany & Zoology (NCERT XI & XII)"], topics:{"Biology":["Cell Biology","Genetics","Ecology","Human Physiology","Plant Physiology","Reproduction","Evolution","Biotechnology"],"Chemistry":["Physical Chemistry","Organic Chemistry","Inorganic Chemistry","Biomolecules"],"Physics":["Mechanics","Thermodynamics","Optics","Modern Physics","Electrostatics"]}, pattern:{duration:"3 hours 20 min",questions:"200 (attempt 180)",total:"720 marks",negative:"Yes (-1)"}, cutoff:[{year:2024,general:720,obc:137,sc:107,st:107},{year:2023,general:720,obc:129,sc:100,st:100}], books:["NCERT Biology XI & XII","DC Pandey – Physics for NEET","OP Tandon – Physical Chemistry","MTG Objective NCERT at Your Fingertips"], eligibility:"Class 12 with PCB. Min age 17.", tips:["NCERT is the bible — every line matters","Biology carries 360/720 marks","Revise with spaced repetition","Attempt full mocks weekly"] },
  { id:"upsc-cse", name:"UPSC CSE", full:"Civil Services Examination", category:"UPSC", color:"#6366f1", icon:"🏛️", difficulty:"Extremely High", diffScore:5, frequency:"Once a year", seats:"~1,000", salary:"₹56,100+ (IAS)", duration:"1-2 years prep", syllabus:["Prelims: GS Paper I, CSAT Paper II","Mains: Essay, GS I-IV, Optional (2 papers)","Interview: Personality Test (275 marks)"], topics:{"History":["Ancient India","Medieval India","Modern India","World History","Art & Culture"],"Geography":["Physical Geography","Indian Geography","World Geography","Environment"],"Polity":["Constitution","Parliament","Judiciary","Federalism","Governance"],"Economy":["Indian Economy","Budget","Planning","Agriculture","Industry"],"Current Affairs":["National","International","Science & Tech","Environment"]}, pattern:{duration:"Prelims: 4hr | Mains: 9 papers",questions:"Prelims 200 MCQs | Mains descriptive",total:"2025 marks (Mains+Interview)",negative:"Prelims: -0.33"}, cutoff:[{year:2024,general:104,obc:98,sc:88,st:84},{year:2023,general:101,obc:95,sc:85,st:81}], books:["NCERT VI-XII Foundation","Laxmikanth – Indian Polity","Spectrum – Modern Indian History","Economic Survey + India Yearbook"], eligibility:"Graduate. Age: 21-32 (Gen).", tips:["Start with NCERTs before standard books","Make concise notes from Day 1","Read The Hindu daily","Choose optional wisely"] },
  { id:"ssc-cgl", name:"SSC CGL", full:"SSC Combined Graduate Level", category:"SSC", color:"#14b8a6", icon:"📋", difficulty:"Moderate", diffScore:2, frequency:"Once a year", seats:"~10,000+", salary:"₹25,000-₹1.5 LPA", duration:"6 months prep", syllabus:["General Intelligence & Reasoning","General Awareness","Quantitative Aptitude","English Comprehension"], topics:{"Reasoning":["Analogy","Series","Coding-Decoding","Puzzles","Blood Relations","Direction","Syllogism"],"Quantitative Aptitude":["Number System","Percentage","Profit & Loss","Ratio","Time & Work","Geometry","Trigonometry"],"General Awareness":["Current Affairs","History","Geography","Polity","Economy","Science"],"English":["Grammar","Vocabulary","Comprehension","Error Detection"]}, pattern:{duration:"Tier I: 60 min | Tier II: 2.5 hr",questions:"Tier I: 100 | Tier II: varies",total:"Tier I: 200 | Tier II: 800",negative:"Yes"}, cutoff:[{year:2024,general:145,obc:138,sc:128,st:120},{year:2023,general:142,obc:135,sc:125,st:117}], books:["Lucent GK","RS Aggarwal – Maths & Reasoning","SP Bakshi – English","Kiran SSC CGL Papers"], eligibility:"Graduate. Age: 18-32.", tips:["Current affairs from last 6 months","Speed & accuracy in Quant","English grammar rules are key","Daily 2 hours practice tests"] },
  { id:"cat", name:"CAT", full:"Common Admission Test", category:"Management", color:"#ec4899", icon:"📊", difficulty:"High", diffScore:3, frequency:"Once a year", seats:"~5,000 (IIMs)", salary:"₹15-50 LPA", duration:"2 years (MBA)", syllabus:["VARC: Reading Comprehension, Para Summary, Para Jumbles","DILR: Data Interpretation, Logical Reasoning","QA: Arithmetic, Algebra, Geometry, Number System"], topics:{"VARC":["Reading Comprehension","Para Summary","Para Jumbles","Odd Sentence Out","Critical Reasoning"],"DILR":["Data Interpretation","Logical Reasoning","Puzzles","Arrangements","Games & Tournaments"],"QA":["Arithmetic","Algebra","Geometry","Number System","Modern Maths"]}, pattern:{duration:"2 hours",questions:"66 questions",total:"198 marks",negative:"Yes (-1 per wrong MCQ)"}, cutoff:[{year:2024,general:99,obc:97,sc:90,st:85},{year:2023,general:99,obc:96,sc:88,st:83}], books:["Arun Sharma – QA & DI","Verbal Ability by Arun Sharma","TIME/CL study material","Previous year CAT papers"], eligibility:"Graduate with min 50% marks (45% SC/ST).", tips:["Accuracy > Speed in this exam","VARC: Read editorials daily","DILR: Practice set-based questions","Attempt 3-4 mocks per week from August"] },
  { id:"gate", name:"GATE", full:"Graduate Aptitude Test in Engineering", category:"Engineering", color:"#f59e0b", icon:"🔬", difficulty:"High", diffScore:3, frequency:"Once a year", seats:"Varies by PSU", salary:"₹6-12 LPA", duration:"2 years (M.Tech)", syllabus:["Core Engineering Subject (branch-specific)","Engineering Mathematics","General Aptitude (Verbal + Numerical)"], topics:{"Engineering Mathematics":["Linear Algebra","Calculus","Differential Equations","Probability","Numerical Methods"],"General Aptitude":["Verbal Ability","Numerical Ability","Reasoning"],"Core Subject":["Data Structures","Algorithms","Operating Systems","Computer Networks","Database"]}, pattern:{duration:"3 hours",questions:"65 questions",total:"100 marks",negative:"Yes (MCQs only)"}, cutoff:[{year:2024,general:31.7,obc:28.5,sc:21.1,st:21.1},{year:2023,general:30.0,obc:27.0,sc:20.0,st:20.0}], books:["Made Easy / ACE Academy notes","Standard textbooks by subject","Previous 15 years GATE papers"], eligibility:"B.E/B.Tech/B.Sc(Research) 3rd year or passed.", tips:["Analyze syllabus weightage first","Engineering Maths is high scoring","Practice numerical answer type questions","Solve subject-wise previous year questions"] },
  { id:"clat", name:"CLAT", full:"Common Law Admission Test", category:"Law", color:"#b45309", icon:"⚖️", difficulty:"High", diffScore:3, frequency:"Once a year", seats:"~2,500 (NLUs)", salary:"₹6-25 LPA", duration:"5 years (LLB)", syllabus:["English Language","Current Affairs & GK","Legal Reasoning","Logical Reasoning","Quantitative Techniques"], topics:{"English":["Reading Comprehension","Vocabulary","Grammar","Critical Reasoning"],"Legal Reasoning":["Legal Principles","Legal Maxims","Constitutional Law","Torts","Contracts"],"Current Affairs":["National","International","Legal Affairs","Important Judgements"],"Logical Reasoning":["Analogy","Syllogism","Assumptions","Conclusions"]}, pattern:{duration:"2 hours",questions:"120 MCQs",total:"120 marks",negative:"Yes (-0.25)"}, cutoff:[{year:2024,general:95,obc:82,sc:65,st:57},{year:2023,general:93,obc:80,sc:63,st:55}], books:["Arihant CLAT guide","AP Bhardwaj – Legal Aptitude","Previous year CLAT papers","The Hindu for Current Affairs"], eligibility:"Class 12 with min 45% marks (40% SC/ST).", tips:["Legal reasoning needs regular practice","Current affairs from last 12 months","Reading comprehension is key","No maths beyond Class 10 level"] },
  { id:"rbi-grade-b", name:"RBI Grade B", full:"Reserve Bank of India Grade B Officer", category:"Banking", color:"#7f1d1d", icon:"🏦", difficulty:"Very High", diffScore:4, frequency:"Once a year", seats:"~200+", salary:"₹55,000-₹1.5 LPA", duration:"8-10 months prep", syllabus:["Phase I: General Awareness, Reasoning, English, Quant","Phase II: Economic & Social Issues, English Writing, Finance & Management"], topics:{"Economics":["Macro Economics","Monetary Policy","Indian Economy","International Trade","RBI Functions"],"Finance":["Financial Markets","Banking Regulations","Financial Instruments","Capital Markets"],"Management":["Management Concepts","HR Management","Organizational Behavior","Ethics"],"General":["Current Affairs","Reasoning","English Writing Skills"]}, pattern:{duration:"Phase I: 3hr | Phase II: descriptive",questions:"Phase I: 200 MCQs | Phase II: written",total:"Phase I: 200 | Phase II: 300",negative:"Phase I: -0.25"}, cutoff:[{year:2024,general:155,obc:142,sc:125,st:118},{year:2023,general:150,obc:137,sc:120,st:113}], books:["Economic Survey India","RBI Annual Report","RBI Grade B previous papers","Ramesh Singh Indian Economy"], eligibility:"Graduate with 60% marks. Age: 21-30.", tips:["Economics and Finance are most important","Read RBI reports and circulars regularly","Phase II needs excellent writing skills","General awareness must be very strong"] },
  { id:"ca-foundation", name:"CA Foundation", full:"Chartered Accountancy Foundation", category:"Commerce", color:"#b91c1c", icon:"💰", difficulty:"Moderate", diffScore:2, frequency:"Twice a year", seats:"No limit", salary:"₹6-25 LPA (after CA)", duration:"4 months prep", syllabus:["Paper 1: Principles & Practice of Accounting","Paper 2: Business Laws & Business Correspondence","Paper 3: Business Mathematics & Logical Reasoning & Statistics","Paper 4: Business Economics & Business & Commercial Knowledge"], topics:{"Accounting":["Accounting Standards","Financial Statements","Partnership","Company Accounts"],"Business Laws":["Indian Contract Act","Sale of Goods Act","Company Law","Business Communication"],"Mathematics":["Algebra","Matrices","Calculus","Statistics","Probability"],"Economics":["Micro Economics","Macro Economics","Indian Economy","Business Knowledge"]}, pattern:{duration:"3 hours per paper",questions:"Paper 1 & 2: Descriptive | Paper 3 & 4: MCQ",total:"400 marks",negative:"Yes for MCQ papers"}, cutoff:[{year:2024,general:200,obc:200,sc:200,st:200},{year:2023,general:200,obc:200,sc:200,st:200}], books:["ICAI Study Material","ICAI Practice Manual","CA Foundation previous papers","Padhuka CA Foundation guide"], eligibility:"Class 12 passed from any stream. No age limit.", tips:["ICAI study material is the primary resource","Accounting and Maths need maximum practice","Paper 3 is objective — accuracy is key","Join a coaching institute for best results"] },
  { id:"nda", name:"NDA", full:"National Defence Academy Examination", category:"Defence", color:"#047857", icon:"⚔️", difficulty:"High", diffScore:3, frequency:"Twice a year", seats:"~400", salary:"₹56,100+ (Lieutenant)", duration:"3 years (NDA)", syllabus:["Mathematics: Algebra, Calculus, Trigonometry, Statistics, Matrices","General Ability: English, GK, Physics, Chemistry, History, Geography"], topics:{"Mathematics":["Algebra","Trigonometry","Calculus","Statistics","Matrices","Analytical Geometry"],"General Ability":["English Grammar","Physics","Chemistry","History","Geography","Current Affairs"]}, pattern:{duration:"5 hours (2 papers)",questions:"Paper I: 120, Paper II: 150",total:"900 marks",negative:"Yes (-0.33)"}, cutoff:[{year:2024,general:360,obc:340,sc:300,st:290},{year:2023,general:350,obc:330,sc:290,st:280}], books:["Pathfinder NDA/NA by Arihant","RS Aggarwal – Maths","Lucent GK","Previous Year NDA Papers"], eligibility:"Class 12 passed/appearing. Age: 16.5-19.5. Only unmarried males.", tips:["Maths paper needs strong basics","GK from last 6 months current affairs","Physical fitness test is important","SSB interview is the toughest part"] },
  { id:"afcat", name:"AFCAT", full:"Air Force Common Admission Test", category:"Defence", color:"#0c4a6e", icon:"✈️", difficulty:"High", diffScore:3, frequency:"Twice a year", seats:"~250+", salary:"₹56,100+ (Flying Officer)", duration:"6 months prep", syllabus:["General Awareness","Verbal Ability in English","Numerical Ability","Reasoning & Military Aptitude"], topics:{"General Awareness":["History","Geography","Polity","Economy","Science","Military Current Affairs"],"Verbal Ability":["Grammar","Vocabulary","Comprehension","Idioms & Phrases"],"Numerical Ability":["Arithmetic","Algebra","Geometry","Data Interpretation"],"Military Aptitude":["Spatial Reasoning","Rotational Figures","Hidden Figures"]}, pattern:{duration:"2 hours",questions:"100 MCQs",total:"300 marks",negative:"Yes (-1)"}, cutoff:[{year:2024,general:170,obc:155,sc:140,st:132},{year:2023,general:165,obc:150,sc:135,st:127}], books:["Arihant AFCAT guide","Previous year AFCAT papers","Lucent GK"], eligibility:"Graduate with 60% marks. Age: 20-24 (flying), 20-26 (ground duty).", tips:["Military aptitude section is unique","Current affairs about defence is important","AFSB interview after written exam","Physical fitness is essential"] },
  { id:"ctet", name:"CTET", full:"Central Teacher Eligibility Test", category:"Teaching", color:"#16a34a", icon:"📚", difficulty:"Moderate", diffScore:2, frequency:"Twice a year", seats:"No limit", salary:"₹35,000-₹1.1 LPA", duration:"3 months prep", syllabus:["Child Development & Pedagogy","Language I (compulsory)","Language II (compulsory)","Mathematics / Science / Social Studies"], topics:{"Child Development":["Growth & Development","Learning Theories","Inclusive Education","Assessment","Motivation"],"Language":["Reading","Writing","Grammar","Comprehension","Language Acquisition"],"Mathematics":["Number System","Geometry","Measurement","Data Handling","Pedagogy"],"EVS/Science":["Environment","Living World","Matter","Pedagogy"]}, pattern:{duration:"2.5 hours",questions:"150 MCQs",total:"150 marks",negative:"No"}, cutoff:[{year:2024,general:90,obc:82,sc:75,st:75},{year:2023,general:88,obc:80,sc:73,st:73}], books:["Child Development by Arihant","NCERT textbooks Class 1-8","Previous year CTET papers","Disha CTET guide"], eligibility:"Class 12 with 50% + D.El.Ed OR Graduation + B.Ed.", tips:["No negative marking — attempt all","Child Development has highest weightage","Pedagogy questions need conceptual clarity","Language sections test teaching methods"] },
  { id:"nata", name:"NATA", full:"National Aptitude Test in Architecture", category:"Architecture", color:"#0369a1", icon:"🏗️", difficulty:"High", diffScore:3, frequency:"Twice a year", seats:"~40,000+", salary:"₹5-15 LPA", duration:"5 years (B.Arch)", syllabus:["Drawing & Composition","Visual Perception & Cognition","Mathematics (Class 11 & 12)","General Aptitude"], topics:{"Drawing":["Perspective Drawing","Architectural Drawing","Sketching","Composition"],"Mathematics":["Algebra","Trigonometry","Coordinate Geometry","Calculus"],"Aptitude":["Visual Perception","Spatial Ability","Critical Thinking","Observation"]}, pattern:{duration:"3 hours",questions:"Part A: Drawing | Part B: MCQ",total:"200 marks",negative:"No"}, cutoff:[{year:2024,general:110,obc:98,sc:82,st:75},{year:2023,general:105,obc:94,sc:78,st:71}], books:["NATA previous year papers","Drawing & sketching practice books","B.Arch entrance guide by Arihant"], eligibility:"Class 12 with Maths. Min 50% marks.", tips:["Drawing is the most important component","Practice perspective drawing daily","Maths up to Class 12 level","Observe architecture and buildings around you"] },
  { id: "ib-sa", 
  name: "IB SA/MT", 
  full: "Intelligence Bureau Security Assistant / Motor Transport", 
  category: "Defence", 
  color: "#1e3a8a", 
  icon: "🕵️", 
  difficulty: "Moderate", 
  diffScore: 2, 
  frequency: "As per vacancy", 
  seats: "Varies", 
  salary: "₹21,700 - ₹69,100", 
  duration: "6-8 months prep", 
  syllabus: ["Tier I: General Awareness, English, Quant, Reasoning", "Tier II: Local Language Translation & Personality Test"], 
  topics: {
    "General Awareness": ["Current Affairs", "Security Issues", "International Relations", "Indian History"],
    "English": ["Grammar", "Comprehension", "Vocabulary"],
    "Reasoning": ["Analytical Ability", "Logic", "Series"]
  }, 
  pattern: {duration: "1 hour (Tier I)", questions: "100 MCQs", total: "100 marks", negative: "Yes (-0.25)"}, 
  cutoff: [{year: 2024, general: 35, obc: 34, sc: 33, st: 33}], 
  books: ["Lucent GK", "R.S. Aggarwal", "Monthly Current Affairs"], 
  eligibility: "Class 10th pass + Local language proficiency.", 
  tips: ["Focus on Current Affairs related to internal security", "Practice local language translation", "Prepare for the personality test/interview"] 
  },
  { 
    id: "sbi-po", 
    name: "SBI PO", 
    full: "State Bank of India Probationary Officer", 
    category: "Banking", 
    color: "#0369a1", 
    icon: "🏦", 
    difficulty: "Very High", 
    diffScore: 4, 
    frequency: "Once a year", 
    seats: "~2,000", 
    salary: "₹12-14 LPA", 
    duration: "6-8 months prep", 
    syllabus: ["Prelims: English, Quant, Reasoning", "Mains: Reasoning & Computer, Data Analysis, Gen/Economy/Banking Awareness, English", "Interview & Group Exercises"], 
    topics: {
      "Reasoning": ["Puzzles", "Seating Arrangement", "Syllogism", "Blood Relations", "Coding-Decoding"],
      "Quantitative Aptitude": ["Data Interpretation", "Number Series", "Quadratic Equations", "Arithmetic", "Simplification"],
      "English": ["Reading Comprehension", "Cloze Test", "Error Spotting", "Para Jumbles"],
      "General Awareness": ["Banking Awareness", "Current Affairs (Last 6 months)", "Static GK", "Financial Awareness"]
    }, 
    pattern: { duration: "Prelims: 1hr | Mains: 3hr", questions: "Prelims: 100 | Mains: 155 + 2 Descriptive", total: "Prelims: 100 | Mains: 250", negative: "Yes (-0.25)" }, 
    cutoff: [{ year: 2023, general: 59.25, obc: 58.25, sc: 52.50, st: 47.75 }, { year: 2022, general: 59.50, obc: 58.25, sc: 52.50, st: 47.75 }], 
    books: ["Word Power Made Easy", "RS Aggarwal - Quantitative Aptitude", "Arihant Banking Awareness", "A Mirror of Common Errors"], 
    eligibility: "Graduate in any discipline. Age: 21-30.", 
    tips: ["Data Interpretation is the game-changer in Mains", "Read financial editorials daily for English & GA", "Practice high-level puzzles under time limits"] 
  },
  { 
    id: "ssc-chsl", 
    name: "SSC CHSL", 
    full: "SSC Combined Higher Secondary Level", 
    category: "SSC", 
    color: "#14b8a6", 
    icon: "📋", 
    difficulty: "Moderate", 
    diffScore: 2, 
    frequency: "Once a year", 
    seats: "~4,000+", 
    salary: "₹30,000 - ₹40,000/month", 
    duration: "4-6 months prep", 
    syllabus: ["Tier I: English, Intelligence, Quant, Gen Awareness", "Tier II: Math, Reasoning, English, GA, Computer, Typing"], 
    topics: {
      "General Intelligence": ["Semantic Analogy", "Venn Diagrams", "Folding & Unfolding", "Number Series"],
      "Quantitative Aptitude": ["Algebra", "Geometry", "Mensuration", "Trigonometry", "Statistical Charts"],
      "English": ["Synonyms/Antonyms", "Spelling Errors", "Idioms & Phrases", "Active/Passive Voice"],
      "General Awareness": ["History", "Culture", "Geography", "Economic Scene", "General Policy", "Scientific Research"]
    }, 
    pattern: { duration: "Tier I: 60 min", questions: "Tier I: 100 MCQs", total: "Tier I: 200 marks", negative: "Yes (-0.50 in Tier I)" }, 
    cutoff: [{ year: 2023, general: 153.91, obc: 152.26, sc: 136.41, st: 124.52 }, { year: 2022, general: 157.72, obc: 153.25, sc: 135.46, st: 125.79 }], 
    books: ["Neetu Singh - English Vol 1", "Kiran SSC CHSL Chapterwise", "Lucent's General Knowledge"], 
    eligibility: "Class 12th passed. Age: 18-27.", 
    tips: ["Typing speed should be practiced from day one", "Previous year papers are gold for SSC", "Focus heavily on English vocabulary"] 
  },
  { 
    id: "rrb-ntpc", 
    name: "RRB NTPC", 
    full: "Railway Recruitment Board Non-Technical Popular Categories", 
    category: "Railway", 
    color: "#b91c1c", 
    icon: "🚆", 
    difficulty: "Moderate", 
    diffScore: 2, 
    frequency: "Varies (Every few years)", 
    seats: "~35,000+", 
    salary: "₹19,900 - ₹35,400 (Basic)", 
    duration: "6 months prep", 
    syllabus: ["CBT 1: Math, Reasoning, General Awareness", "CBT 2: Math, Reasoning, General Awareness (Higher difficulty)"], 
    topics: {
      "Mathematics": ["Number System", "Decimals", "Fractions", "LCM/HCF", "Ratio & Proportions", "Percentage", "Time & Work"],
      "Reasoning": ["Analogies", "Completion of Number/Alphabet Series", "Coding-Decoding", "Mathematical Operations"],
      "General Awareness": ["Current Events", "Indian Railways Facts", "Games & Sports", "Art & Culture of India", "Indian Literature", "General Science"]
    }, 
    pattern: { duration: "CBT 1: 90 mins", questions: "CBT 1: 100 MCQs", total: "CBT 1: 100 marks", negative: "Yes (-1/3)" }, 
    cutoff: [{ year: 2021, general: 75, obc: 70, sc: 62, st: 56 }, { year: 2016, general: 77, obc: 72, sc: 63, st: 58 }], 
    books: ["Fast Track Objective Arithmetic - Rajesh Verma", "Lucent's GK", "RS Aggarwal - Verbal & Non-Verbal Reasoning"], 
    eligibility: "Class 12th or Graduate (depends on post). Age: 18-30/33.", 
    tips: ["General Awareness holds the maximum weightage", "Speed and accuracy in calculation are crucial", "Review Indian Railway history and current projects"] 
  },
  { 
    id: "ib-acio", 
    name: "IB ACIO", 
    full: "Intelligence Bureau Assistant Central Intelligence Officer", 
    category: "Defence", 
    color: "#1e3a8a", 
    icon: "🕵️‍♂️", 
    difficulty: "High", 
    diffScore: 3, 
    frequency: "As per vacancy", 
    seats: "~900+", 
    salary: "₹44,900 - ₹1,42,400", 
    duration: "6-8 months prep", 
    syllabus: ["Tier I: Current Affairs, General Studies, Numerical Aptitude, Reasoning, English", "Tier II: Essay, English Comprehension & Précis writing", "Tier III: Interview"], 
    topics: {
      "General Awareness": ["Internal Security", "Geopolitics", "Current Affairs", "Indian Polity & Constitution"],
      "Quantitative Aptitude": ["Arithmetic", "Mensuration", "Data Interpretation", "Algebra"],
      "Reasoning": ["Analytical Reasoning", "Pattern Completion", "Syllogism"],
      "English": ["Grammar", "Vocabulary", "Reading Comprehension"]
    }, 
    pattern: { duration: "Tier I: 1 hour", questions: "Tier I: 100 MCQs", total: "Tier I: 100 marks", negative: "Yes (-0.25)" }, 
    cutoff: [{ year: 2021, general: 65, obc: 60, sc: 50, st: 50 }, { year: 2017, general: 65, obc: 60, sc: 50, st: 50 }], 
    books: ["Spectrum - Modern History", "Word Power Made Easy", "Lucent GK", "Manorama Yearbook"], 
    eligibility: "Graduate in any stream. Age: 18-27.", 
    tips: ["Tier II descriptive writing is a major elimination round", "Current affairs regarding national security are critical", "Interview focuses heavily on psychological profile and GK"] 
  },
  { 
    id: "lic-aao", 
    name: "LIC AAO", 
    full: "Life Insurance Corporation Assistant Administrative Officer", 
    category: "Insurance", 
    color: "#d97706", 
    icon: "🛡️", 
    difficulty: "High", 
    diffScore: 3, 
    frequency: "Varies", 
    seats: "~300", 
    salary: "₹92,870/month", 
    duration: "6 months prep", 
    syllabus: ["Prelims: Reasoning, Quant, English (Qualifying)", "Mains: Reasoning, GK, Data Analysis, Insurance/Financial Market Awareness", "Descriptive Paper"], 
    topics: {
      "Insurance & Financial Awareness": ["History of LIC", "Insurance Terminology", "Financial Markets", "Current Banking News"],
      "Reasoning": ["Machine Input/Output", "Puzzles", "Seating Arrangement", "Inequalities"],
      "Data Analysis & Interpretation": ["Pie Charts", "Bar Graphs", "Caselets", "Data Sufficiency"],
      "General Knowledge": ["Current Affairs", "Static GK", "Economic Policies"]
    }, 
    pattern: { duration: "Prelims: 1hr", questions: "Prelims: 100 MCQs", total: "Prelims: 70 marks (English not counted)", negative: "No negative marking in Prelims" }, 
    cutoff: [{ year: 2023, general: 58, obc: 54, sc: 50, st: 46 }, { year: 2019, general: 58, obc: 54, sc: 50, st: 46 }], 
    books: ["Insurance Awareness by Disha", "RS Aggarwal Quantitative Aptitude", "Banking Awareness by Arihant"], 
    eligibility: "Bachelor's Degree in any discipline. Age: 21-30.", 
    tips: ["English is only qualifying in Prelims—focus marks on Quant/Reasoning", "Insurance awareness is the key to cracking Mains", "Practice descriptive writing for insurance sector topics"] 
  },
  { 
    id: "ibps-po", 
    name: "IBPS PO", 
    full: "Institute of Banking Personnel Selection Probationary Officer", 
    category: "Banking", 
    color: "#be123c", 
    icon: "🏦", 
    difficulty: "High", 
    diffScore: 3, 
    frequency: "Once a year", 
    seats: "~3,000+", 
    salary: "₹52,000 - ₹55,000/month", 
    duration: "6 months prep", 
    syllabus: ["Prelims: English, Quant, Reasoning", "Mains: Reasoning & Computer, General/Economy/Banking Awareness, English, Data Analysis", "Interview"], 
    topics: {
      "Reasoning": ["Puzzles", "Seating Arrangement", "Inequalities", "Syllogism", "Blood Relations"],
      "Quantitative Aptitude": ["Data Interpretation", "Quadratic Equations", "Number Series", "Approximation", "Arithmetic"],
      "English Language": ["Reading Comprehension", "Error Spotting", "Cloze Test", "Para Jumbles"],
      "General Awareness": ["Banking Awareness", "Financial Awareness", "Current Affairs (Last 6 months)"]
    }, 
    pattern: { duration: "Prelims: 1hr | Mains: 3.5hr", questions: "Prelims: 100 | Mains: 155 + 2 Descriptive", total: "Prelims: 100 | Mains: 225", negative: "Yes (-0.25)" }, 
    cutoff: [{ year: 2023, general: 54.25, obc: 54.25, sc: 49.00, st: 43.00 }, { year: 2022, general: 49.75, obc: 49.75, sc: 46.75, st: 40.75 }], 
    books: ["Word Power Made Easy", "RS Aggarwal - Quantitative Aptitude", "Banking Awareness by Arihant"], 
    eligibility: "Graduate in any discipline. Age: 20-30.", 
    tips: ["Speed is crucial for Prelims; accuracy is the key for Mains", "Practice daily Data Interpretation sets", "Read a financial newspaper daily for General Awareness and English"] 
  },
  { 
    id: "gpsc-class-1-2", 
    name: "GPSC Class 1 & 2", 
    full: "Gujarat Public Service Commission Class 1 & 2", 
    category: "State PSC", 
    color: "#b45309", 
    icon: "🏛️", 
    difficulty: "Very High", 
    diffScore: 4, 
    frequency: "Once a year", 
    seats: "~100 - 300 (Varies)", 
    salary: "₹56,100+ (Class 1)", 
    duration: "1-2 years prep", 
    syllabus: ["Prelims: General Studies 1 & 2", "Mains: Gujarati, English, Essay, GS 1, GS 2, GS 3", "Interview"], 
    topics: {
      "History & Culture": ["Indus Valley in Gujarat", "Sultanate & Mughal Period in Gujarat", "Freedom Movement in Gujarat", "Art and Architecture of Gujarat"],
      "Polity & Economy": ["Indian Constitution", "Panchayati Raj", "Gujarat Economy", "NITI Aayog"],
      "Geography": ["Physical Geography of India & Gujarat", "Economic Geography", "Social Geography"],
      "Science & Tech": ["ICT", "Space & Defense", "Environment & Ecology", "Current Events"]
    }, 
    pattern: { duration: "Prelims: 6hr (2 papers) | Mains: 18hr (6 papers)", questions: "Prelims: 400 MCQs | Mains: Descriptive", total: "Prelims: 400 | Mains: 900", negative: "Yes (-0.33 in Prelims)" }, 
    cutoff: [{ year: 2023, general: 184.77, obc: 184.77, sc: 184.77, st: 169.73 }, { year: 2022, general: 145.33, obc: 145.33, sc: 145.33, st: 119.53 }], 
    books: ["Granth Nirman Board Textbooks (History & Geography)", "Laxmikanth - Indian Polity", "Liberty Publications GS Material", "Gujarat Samachar for Current Affairs"], 
    eligibility: "Graduate in any discipline. Age: 20-36 (Gen). Knowledge of Gujarati/Hindi.", 
    tips: ["Focus heavily on Gujarat's specific history, geography, and economy", "Practice descriptive writing in Gujarati for Mains", "Analyze previous 5 years' GPSC papers thoroughly"] 
  },
  { 
    id: "rrb-group-d", 
    name: "RRB Group D", 
    full: "Railway Recruitment Board Group D", 
    category: "Railway", 
    color: "#9f1239", 
    icon: "🚂", 
    difficulty: "Easy", 
    diffScore: 1, 
    frequency: "Varies", 
    seats: "~1 Lakh+", 
    salary: "₹18,000 (Basic) + Allowances", 
    duration: "3-4 months prep", 
    syllabus: ["Computer Based Test: General Science, Mathematics, General Intelligence & Reasoning, General Awareness"], 
    topics: {
      "General Science": ["Physics (Class 10 level)", "Chemistry (Class 10 level)", "Life Sciences (Class 10 level)"],
      "Mathematics": ["BODMAS", "Fractions", "Percentages", "Mensuration", "Time and Work", "Simple/Compound Interest"],
      "Reasoning": ["Alphabetical Series", "Coding and Decoding", "Venn Diagram", "Data Interpretation"],
      "General Awareness": ["Sports", "Indian Economy", "Indian Personalities", "Science & Technology Current Affairs"]
    }, 
    pattern: { duration: "90 mins", questions: "100 MCQs", total: "100 marks", negative: "Yes (-1/3)" }, 
    cutoff: [{ year: 2022, general: 71, obc: 66, sc: 60, st: 55 }, { year: 2018, general: 74, obc: 69, sc: 61, st: 56 }], 
    books: ["Lucent's General Science", "RS Aggarwal - Mathematics", "Arihant RRB Group D Guide"], 
    eligibility: "Class 10th pass OR ITI from institutions recognized by NCVT/SCVT. Age: 18-33.", 
    tips: ["General Science is a major scoring area; master Class 9 & 10 NCERT", "Maintain physical fitness for the Physical Efficiency Test (PET)", "Take daily online mock tests to improve speed"] 
  },
  { 
    id: "sbi-clerk", 
    name: "SBI Clerk", 
    full: "State Bank of India Junior Associate", 
    category: "Banking", 
    color: "#0284c7", 
    icon: "🏦", 
    difficulty: "Moderate", 
    diffScore: 2, 
    frequency: "Once a year", 
    seats: "~8,000+", 
    salary: "₹30,000 - ₹35,000/month", 
    duration: "4-6 months prep", 
    syllabus: ["Prelims: English, Numerical Ability, Reasoning", "Mains: General/Financial Awareness, English, Quant, Reasoning & Computer Aptitude"], 
    topics: {
      "Numerical Ability": ["Simplification", "Data Interpretation", "Number Series", "Quadratic Equations", "Arithmetic"],
      "Reasoning": ["Seating Arrangement", "Puzzles", "Alphanumeric Series", "Syllogism", "Inequalities"],
      "English Language": ["Reading Comprehension", "Error Spotting", "Fill in the blanks", "Para Jumbles"],
      "General Awareness": ["Static GK", "Current Affairs", "Financial Awareness", "Banking Terminology"]
    }, 
    pattern: { duration: "Prelims: 1hr | Mains: 2hr 40min", questions: "Prelims: 100 | Mains: 190", total: "Prelims: 100 | Mains: 200", negative: "Yes (-0.25)" }, 
    cutoff: [{ year: 2023, general: 74.5, obc: 74.5, sc: 63.5, st: 58.0 }, { year: 2022, general: 82.5, obc: 82.5, sc: 70.0, st: 65.0 }], 
    books: ["Quicker Maths by M. Tyra", "A Modern Approach to Verbal & Non-Verbal Reasoning by RS Aggarwal", "Objective General English by SP Bakshi"], 
    eligibility: "Graduate in any discipline. Age: 20-28.", 
    tips: ["Simplification and Approximation are quick marks in Prelims", "Sectional timing requires excellent time management", "Must be proficient in the local language of the applied state"] 
  },
  { 
    id: "isro-sc", 
    name: "ISRO Scientist/Engineer", 
    full: "ISRO Scientist/Engineer (SC)", 
    category: "PSUs & Technical", 
    color: "#4f46e5", 
    icon: "🚀", 
    difficulty: "Very High", 
    diffScore: 4, 
    frequency: "Varies", 
    seats: "~200-300", 
    salary: "₹56,100 (Basic) + Allowances", 
    duration: "8-10 months prep", 
    syllabus: ["Written Test: Core Engineering Subject (Mechanical/Electronics/Computer Science)", "Interview"], 
    topics: {
      "Engineering Mathematics": ["Calculus", "Linear Algebra", "Differential Equations", "Probability and Statistics"],
      "Core Mechanical": ["Thermodynamics", "Fluid Mechanics", "Strength of Materials", "Manufacturing"],
      "Core Electronics": ["Analog Circuits", "Digital Electronics", "Signals and Systems", "Electromagnetics"],
      "Core Computer Science": ["Data Structures", "Algorithms", "Operating Systems", "Computer Networks"]
    }, 
    pattern: { duration: "90 mins", questions: "80 MCQs", total: "240 marks", negative: "Yes (-1)" }, 
    cutoff: [{ year: 2020, general: 139, obc: 135, sc: 110, st: 105 }, { year: 2018, general: 119, obc: 115, sc: 95, st: 90 }], 
    books: ["GATE previous year papers", "Standard core engineering textbooks", "Made Easy publications"], 
    eligibility: "B.E/B.Tech in relevant branch with min 65% marks or 6.84 CGPA. Age: Max 28 years.", 
    tips: ["The exam pattern is very similar to GATE but focuses more on speed", "Previous 10 years ISRO papers are mandatory to solve", "Interview carries significant weightage and tests deep core concepts"] 
  },
    { 
    id: "rrb-alp", 
    name: "RRB ALP", 
    full: "Railway Recruitment Board Assistant Loco Pilot", 
    category: "Railway", 
    color: "#b91c1c", 
    icon: "🚆", 
    difficulty: "Moderate", 
    diffScore: 2, 
    frequency: "Varies", 
    seats: "~18,000+", 
    salary: "₹19,900 (Basic) + High Allowances", 
    duration: "6 months prep", 
    syllabus: ["CBT 1: Math, Reasoning, General Science, General Awareness", "CBT 2: Part A (Core subjects) + Part B (Trade Test)", "CBAT: Computer Based Aptitude Test"], 
    topics: {
      "Mathematics": ["Number System", "BODMAS", "Algebra", "Geometry", "Trigonometry"],
      "Reasoning": ["Analogies", "Coding-Decoding", "Syllogism", "Venn Diagrams", "Statement & Arguments"],
      "General Science": ["Physics", "Chemistry", "Life Sciences (Class 10 level)"],
      "General Awareness": ["Current Affairs", "Science & Technology", "Sports", "Culture"]
    }, 
    pattern: { duration: "CBT 1: 60 mins | CBT 2: 2.5 hrs", questions: "CBT 1: 75 | CBT 2: 175", total: "CBT 1: 75 marks | CBT 2: 175 marks", negative: "Yes (-1/3)" }, 
    cutoff: [{ year: 2018, general: 45, obc: 35, sc: 32, st: 28 }, { year: 2014, general: 48, obc: 38, sc: 34, st: 30 }], 
    books: ["Lucent's General Science", "RS Aggarwal - Quantitative Aptitude", "Platform Series RRB ALP Book"], 
    eligibility: "Matriculation / SSLC plus ITI/Diploma/Degree in relevant trade. Age: 18-30.", 
    tips: ["Part B of CBT 2 is qualifying but absolutely crucial—don't ignore your technical trade", "Focus heavily on basic Physics and Engineering Drawing", "Practice psychological/spatial tests daily before the CBAT"] 
  },
  { 
    id: "ssc-mts", 
    name: "SSC MTS", 
    full: "SSC Multi-Tasking (Non-Technical) Staff", 
    category: "SSC", 
    color: "#0d9488", 
    icon: "📋", 
    difficulty: "Easy", 
    diffScore: 1, 
    frequency: "Once a year", 
    seats: "~8,000+", 
    salary: "₹18,000 - ₹22,000/month", 
    duration: "3-4 months prep", 
    syllabus: ["Session-I: Numerical & Mathematical Ability, Reasoning", "Session-II: General Awareness, English Language"], 
    topics: {
      "Numerical Ability": ["Integers", "LCM/HCF", "Decimals", "Percentage", "Time & Work"],
      "Reasoning": ["Alpha-Numeric Series", "Coding & Decoding", "Analogy", "Pattern Completion"],
      "English": ["Vocabulary", "Grammar", "Synonyms/Antonyms", "Comprehension"],
      "General Awareness": ["Art & Culture", "History", "Geography", "Civics (10th Std level)"]
    }, 
    pattern: { duration: "90 mins (45 min per session)", questions: "90 MCQs", total: "150 marks (Session II only)", negative: "Session I: No | Session II: Yes (-1)" }, 
    cutoff: [{ year: 2023, general: 130, obc: 128, sc: 120, st: 110 }, { year: 2022, general: 125, obc: 122, sc: 115, st: 105 }], 
    books: ["Lucent's GK", "Neetu Singh English Vol 1", "Kiran SSC MTS Previous Year Solved Papers"], 
    eligibility: "Class 10th passed. Age: 18-25 or 18-27 (depends on department).", 
    tips: ["Session-I is only qualifying—focus maximum energy on scoring high in Session-II (English & GA)", "Vocabulary is a game changer in the English section", "Attempt maximum mocks for time management"] 
  },
  { 
    id: "ugc-net", 
    name: "UGC NET", 
    full: "University Grants Commission National Eligibility Test", 
    category: "Teaching", 
    color: "#16a34a", 
    icon: "🎓", 
    difficulty: "High", 
    diffScore: 3, 
    frequency: "Twice a year", 
    seats: "Qualifying (Top 6% NET, Top 1% JRF)", 
    salary: "₹37,000/month (JRF) / Asst. Prof Salary", 
    duration: "6 months prep", 
    syllabus: ["Paper 1: Teaching & Research Aptitude (Common)", "Paper 2: Subject Specific (80+ subjects available)"], 
    topics: {
      "Teaching Aptitude": ["Methods of Teaching", "Evaluation Systems", "Learner Characteristics"],
      "Research Aptitude": ["Types of Research", "Thesis Writing", "Research Ethics"],
      "Logical Reasoning": ["Venn Diagram", "Indian Logic (Pramanas)", "Analogies"],
      "Data Interpretation": ["Graphical representation", "Data Mapping"]
    }, 
    pattern: { duration: "3 hours", questions: "150 MCQs (50 in P1 + 100 in P2)", total: "300 marks", negative: "No" }, 
    cutoff: [{ year: 2023, general: 198, obc: 184, sc: 172, st: 166 }, { year: 2022, general: 200, obc: 186, sc: 174, st: 168 }], 
    books: ["KVS Madaan - NTA UGC NET Paper 1", "Trueman's specific subject guide", "Previous 10 Years Solved Papers"], 
    eligibility: "Master's Degree with minimum 55% marks. Age: No limit for NET, max 30 for JRF.", 
    tips: ["Since there is no negative marking, attempt 100% of the questions", "Paper 1 is highly scoring, do not ignore it for your core subject", "Indian Logic is a crucial and repetitive topic in Paper 1"] 
  },
  { 
    id: "ibps-clerk", 
    name: "IBPS Clerk", 
    full: "Institute of Banking Personnel Selection Clerk", 
    category: "Banking", 
    color: "#0284c7", 
    icon: "🏦", 
    difficulty: "Moderate", 
    diffScore: 2, 
    frequency: "Once a year", 
    seats: "~6,000+", 
    salary: "₹30,000 - ₹32,000/month", 
    duration: "4-6 months prep", 
    syllabus: ["Prelims: English, Numerical Ability, Reasoning", "Mains: General/Financial Awareness, General English, Reasoning & Computer, Quantitative Aptitude"], 
    topics: {
      "Numerical Ability": ["Simplification", "Number Series", "Data Interpretation", "Arithmetic"],
      "Reasoning": ["Syllogism", "Inequalities", "Puzzles", "Seating Arrangement"],
      "English Language": ["Reading Comprehension", "Cloze Test", "Error Spotting"],
      "General Awareness": ["Current Affairs", "Banking Awareness", "Static GK"]
    }, 
    pattern: { duration: "Prelims: 60 mins | Mains: 160 mins", questions: "Prelims: 100 | Mains: 190", total: "Prelims: 100 | Mains: 200", negative: "Yes (-0.25)" }, 
    cutoff: [{ year: 2023, general: 78.5, obc: 78.5, sc: 70.0, st: 65.0 }, { year: 2022, general: 80.5, obc: 80.5, sc: 71.5, st: 66.0 }], 
    books: ["RS Aggarwal Quantitative Aptitude", "Word Power Made Easy", "Arihant Banking Awareness"], 
    eligibility: "Graduate in any discipline. Age: 20-28. Proficiency in local language is mandatory.", 
    tips: ["Speed in Simplification and Number Series defines Prelims success", "Mains level GA requires daily reading of current affairs", "Sectional cutoffs exist, so you must balance all subjects"] 
  },
  { 
    id: "gsssb-clerk", 
    name: "Bin Sachivalay Clerk", 
    full: "GSSSB Bin Sachivalay Clerk & Office Assistant", 
    category: "State PSC", 
    color: "#ea580c", 
    icon: "🏢", 
    difficulty: "Moderate", 
    diffScore: 2, 
    frequency: "Varies", 
    seats: "~3,000+", 
    salary: "₹26,000/month (Fixed for initial years)", 
    duration: "6 months prep", 
    syllabus: ["Written Exam: Gujarat History/Culture, Gujarati Grammar, English Grammar, Indian Polity, Current Affairs, Computer Basics", "Computer Proficiency Test (CPT)"], 
    topics: {
      "Gujarat History & Culture": ["Mahagujarat Movement", "Folk dances of Gujarat", "Solanki Era"],
      "Polity": ["Panchayati Raj", "Constitution Articles", "Fundamental Rights"],
      "Language": ["Gujarati Chhand, Alankar, Samas", "English Tenses, Active/Passive"],
      "Computer Knowledge": ["MS Office", "Internet Basics", "Shortcuts"]
    }, 
    pattern: { duration: "2 hours", questions: "200 MCQs", total: "200 marks", negative: "Yes (-0.25)" }, 
    cutoff: [{ year: 2022, general: 118.5, obc: 114.2, sc: 110.5, st: 92.0 }, { year: 2019, general: 122.0, obc: 118.5, sc: 115.0, st: 95.0 }], 
    books: ["Liberty GSSSB Book", "Akshar Publication Gujarati Vyakaran", "ICE Rajkot Current Affairs"], 
    eligibility: "Graduate. Age: 18-33. Basic computer certificate required.", 
    tips: ["Gujarat History and Polity carry a huge chunk of marks", "Gujarati Vyakaran (Grammar) is highly scoring if rules are memorized", "Computer basics must not be ignored for the written test"] 
  },

];
